### ISSUE TITLE
Create correct size dataset

### ISSUE THREAD

**Issue by nsrazdan** [nsrazdan/ML_Hanabi#2]
As Aron states [here](https://piazza.com/class/jxihjxq4tsr67i?cid=14):
```
num_rainbow_agents = 6
num_unique_agents = 1
num_train_games = 10
num_test_games = 100
num_validation_games = ???
num_total_games = num_train_games + num_test_games + num_validation_games
```
So we need to generate ```num_total_games``` of data for each rainbow agent
So we will have 6 instances of our functional model, one for each rainbow agent

**Comment by nsrazdan** [comment]
We need to figure out the ```num_validation_games``` above

**Comment by huyenpham2995** [comment]
I asked Aron about this. So we generate 10 games for validation and train, 100 games for testing. All those games come from the same agent. Our load_data now is doing that, so Im gonna close this

**Comment by nsrazdan** [comment]
Sweet!
