### ISSUE TITLE
Increase accuracy of model

### ISSUE THREAD

**Issue by nsrazdan** [nsrazdan/ML_Hanabi#6]

**Comment by huyenpham2995** [comment]
Best result so far:
Agent 1: 0.3659
Agent 2: 0.4105
Agent 3: 0.3663
Agent 4: 0.3821
Agent 5: 0.3356 (this one is tough)
Agent 6: 0.4495 (yaaay)

**Comment by nsrazdan** [comment]
made the most efficient without taking too much time before deadline
